package com.projectapp.lessons._6_Exception;

/**Вложение операторов try может быть не так очевидным при вызовах методов.
 Например, вызов метода можно заключить в блок оператора try, а в теле этого
 метода организовать еще один блок оператора try.
 В этом случае блок оператора try в теле метода оказывается вложенным
 во внешний блок оператора try, откуда вызывается этот метод

 СДЕЛАЙ САМОСТОЯТЕЛЬНО! :)
 */
public class A4_Exception_Inner {
}
